from PyQt5 import QtCore, QtGui, QtWidgets
from islemler import *

class Ui_FormAmeliyatIslemleri(object):

    def gocombo(self):
        global combo
        combo = self.comboBox.currentText()

    def onaylaButon(self, genel, beyin, kalp):
        if genel:
            self.window = QtWidgets.QWidget()
            self.ui = Ui_FormIslemler(combo,"Genel Cerrahi")
            self.ui.setupUi(self.window)
            self.window.show()
        elif beyin:
            self.window = QtWidgets.QWidget()
            self.ui = Ui_FormIslemler(combo,"Beyin Cerrahi")
            self.ui.setupUi(self.window)
            self.window.show()
        elif kalp:
            self.window = QtWidgets.QWidget()
            self.ui = Ui_FormIslemler(combo,"Kalp Cerrahi")
            self.ui.setupUi(self.window)
            self.window.show()
        else:
            pass

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(622, 347)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Form.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        Form.setFont(font)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 20, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 80, 331, 151))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(400, 80, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.activated[str].connect(self.gocombo)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(390, 30, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(260, 270, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda: self.onaylaButon(self.radioButton.isChecked(),
                                                                 self.radioButton_2.isChecked(),
                                                                 self.radioButton_3.isChecked()))
        self.label.raise_()
        self.horizontalLayoutWidget.raise_()
        self.comboBox.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Ameliyat İşlemleri"))
        self.label.setText(_translate("Form", "Ameliyat türünü seçiniz."))
        self.radioButton_2.setText(_translate("Form", "Beyin Cerrahi"))
        self.radioButton.setText(_translate("Form", "Genel Cerrahi"))
        self.radioButton_3.setText(_translate("Form", "Kalp Cerrahi"))
        self.comboBox.setItemText(1, _translate("Form", "Afyonkarahisar"))
        self.comboBox.setItemText(2, _translate("Form", "Ağrı"))
        self.comboBox.setItemText(3, _translate("Form", "Ankara"))
        self.comboBox.setItemText(4, _translate("Form", "Bolu"))
        self.comboBox.setItemText(5, _translate("Form", "Bursa"))
        self.comboBox.setItemText(6, _translate("Form", "Edirne"))
        self.comboBox.setItemText(7, _translate("Form", "Erzurum"))
        self.comboBox.setItemText(8, _translate("Form", "Giresun"))
        self.comboBox.setItemText(9, _translate("Form", "İstanbul"))
        self.comboBox.setItemText(10, _translate("Form", "İzmir"))
        self.comboBox.setItemText(11, _translate("Form", "Kars"))
        self.comboBox.setItemText(12, _translate("Form", "Kocaeli"))
        self.comboBox.setItemText(13, _translate("Form", "Kayseri"))
        self.comboBox.setItemText(14, _translate("Form", "Mardin"))
        self.comboBox.setItemText(15, _translate("Form", "Mersin"))
        self.comboBox.setItemText(16, _translate("Form", "Ordu"))
        self.comboBox.setItemText(17, _translate("Form", "Rize"))
        self.comboBox.setItemText(18, _translate("Form", "Sakarya"))
        self.comboBox.setItemText(19, _translate("Form", "Sinop"))
        self.comboBox.setItemText(20, _translate("Form", "Sivas"))
        self.comboBox.setItemText(21, _translate("Form", "Tekirdağ"))
        self.comboBox.setItemText(22, _translate("Form", "Tokat"))
        self.comboBox.setItemText(23, _translate("Form", "Trabzon"))
        self.comboBox.setItemText(24, _translate("Form", "Van"))
        self.label_2.setText(_translate("Form", "Ameliyat olunacak ili seçiniz"))
        self.pushButton.setText(_translate("Form", "Onayla"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_FormAmeliyatIslemleri()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
