from PyQt5.QtWidgets import *
from Sponsorluklar import *
from YöneticiMesajı import *
from İletişim import *
from Ameliyatİşlemleri import *
from Doktorlar import *
from YöneticiGirişi import *
from Yorumlar import *
from Puanlama import *


class Ui_MainWindow(object):
    def openPuanlama(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_FormKaydet()
        self.ui.setupUi(self.window)
        self.window.show()

    def openDoktorlar(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_FormDoktorlar()
        self.ui.setupUi(self.window)
        self.window.show()

    def openSponsorluklar(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_FormSponsorluklar()
        self.ui.setupUi(self.window)
        self.window.show()

    def openYoneticiMesaji(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_FormYoneticiMesaji()
        self.ui.setupUi(self.window)
        self.window.show()

    def openIletisim(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_FormIletisim()
        self.ui.setupUi(self.window)
        self.window.show()

    def cikisYap(self):
        sys.exit()

    def openYoneticiGirisi(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_FormYoneticiGirisi()
        self.ui.setupUi(self.window)
        self.window.show()

    def openAmeliyatIslemleri(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_FormAmeliyatIslemleri()
        self.ui.setupUi(self.window)
        self.window.show()

    def openYorumlar(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_FormYorum()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(656, 428)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 270, 651, 90))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 800, 270))
        self.label_5.setPixmap(QtGui.QPixmap("ameliyat.jpg"))
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton.clicked.connect(self.openAmeliyatIslemleri)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_2.clicked.connect(self.openDoktorlar)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 360, 151, 31))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 100, 521, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(530, 0, 121, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 20, 131, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 656, 21))
        self.menubar.setObjectName("menubar")
        self.menuGenel = QtWidgets.QMenu(self.menubar)
        self.menuGenel.setObjectName("menuGenel")
        self.menuHakk_m_zda = QtWidgets.QMenu(self.menubar)
        self.menuHakk_m_zda.setObjectName("menuHakk_m_zda")
        self.menuYard_m = QtWidgets.QMenu(self.menubar)
        self.menuYard_m.setObjectName("menuYard_m")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSponsorluklar = QtWidgets.QAction(MainWindow)
        self.actionSponsorluklar.setObjectName("actionSponsorluklar")
        self.actionSponsorluklar.triggered.connect(self.openSponsorluklar)
        self.actionYorumlar = QtWidgets.QAction(MainWindow)
        self.actionYorumlar.setObjectName("actionYorumlar")
        self.actionIletisim = QtWidgets.QAction(MainWindow)
        self.actionIletisim.setObjectName("actionIletisim")
        self.actionIletisim = QtWidgets.QAction(MainWindow)
        self.actionIletisim.setObjectName("actionIletisim")

        self.actionPuanlama = QtWidgets.QAction(MainWindow)
        self.actionPuanlama.setObjectName("actionPuanlama")
        self.actionPuanlama = QtWidgets.QAction(MainWindow)
        self.actionPuanlama.setObjectName("actionPuanlama")
        self.actionPuanlama.triggered.connect(self.openPuanlama)

        self.actionIletisim.triggered.connect(self.openIletisim)
        self.actionYorumlar_2 = QtWidgets.QAction(MainWindow)
        self.actionYorumlar_2.setObjectName("actionYorumlar_2")
        self.actionYorumlar_2.triggered.connect(self.openYorumlar)
        self.actionY_netici_Giri_i = QtWidgets.QAction(MainWindow)
        self.actionY_netici_Giri_i.setObjectName("actionY_netici_Giri_i")
        self.actionY_netici_Giri_i.triggered.connect(self.openYoneticiGirisi)
        self.action_k = QtWidgets.QAction(MainWindow)
        self.action_k.setShortcut("")
        self.action_k.setAutoRepeat(True)
        self.action_k.setVisible(True)
        self.action_k.setObjectName("action_k")
        self.action_k.triggered.connect(self.cikisYap)
        self.actionY_netici_Mesaj = QtWidgets.QAction(MainWindow)
        self.actionY_netici_Mesaj.setObjectName("actionY_netici_Mesaj")
        self.actionY_netici_Mesaj.triggered.connect(self.openYoneticiMesaji)
        self.menuGenel.addAction(self.actionSponsorluklar)
        self.menuGenel.addAction(self.actionY_netici_Giri_i)
        self.menuGenel.addAction(self.action_k)
        self.menuHakk_m_zda.addAction(self.actionY_netici_Mesaj)
        self.menuYard_m.addAction(self.actionIletisim)
        self.menuYard_m.addAction(self.actionPuanlama)
        self.menuYard_m.addAction(self.actionYorumlar_2)
        self.menubar.addAction(self.menuGenel.menuAction())
        self.menubar.addAction(self.menuHakk_m_zda.menuAction())
        self.menubar.addAction(self.menuYard_m.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Surgery Operation"))
        self.pushButton.setText(_translate("MainWindow", "Ameliyat İşlemleri"))
        self.pushButton_2.setText(_translate("MainWindow", "Doktorlar"))
        self.label_2.setText(_translate("MainWindow", "Gizliliğiniz bizim için önemlidir. "))
        self.label.setText(_translate("MainWindow", "Sağlığınız bizim için önemlidir..."))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 10, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        self.label_3.setText(_translate("MainWindow", "+90 507 574 13 88"))
        self.label_4.setText(_translate("MainWindow", "Bizi arayın!"))
        self.menuGenel.setTitle(_translate("MainWindow", "Genel"))
        self.menuHakk_m_zda.setTitle(_translate("MainWindow", "Hakkımızda"))
        self.menuYard_m.setTitle(_translate("MainWindow", "Yardım"))
        self.actionSponsorluklar.setText(_translate("MainWindow", "Sponsorluklar"))
        self.actionYorumlar.setText(_translate("MainWindow", "Yorumlar"))
        self.actionIletisim.setText(_translate("MainWindow", "İletişim"))
        self.actionIletisim.setText(_translate("MainWindow", "İletişim"))

        self.actionPuanlama.setText(_translate("MainWindow", "Puanlama"))
        self.actionPuanlama.setText(_translate("MainWindow", "Puanlama"))

        self.actionYorumlar_2.setText(_translate("MainWindow", "Yorumlar"))
        self.actionY_netici_Giri_i.setText(_translate("MainWindow", "Yönetici Girişi"))
        self.action_k.setText(_translate("MainWindow", "Çıkış"))
        self.actionY_netici_Mesaj.setText(_translate("MainWindow", "Yönetici Mesajı"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


